### ISSUE TITLE
Unable to make falcon_main

### ISSUE THREAD

**Issue by tomBlueOrange** [cmp-nct/ggllm.cpp#10]
I am trying to build this on Ubuntu 20.04.6 LTS. When I run make falcon_main I get the following error:

examples/falcon/falcon_main.cpp: In function ‘int main(int, char**)’:
examples/falcon/falcon_main.cpp:402:17: error: ‘ggml_cuda_pool_free_all’ was not declared in this scope
  402 |                 ggml_cuda_pool_free_all(-1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
examples/falcon/falcon_main.cpp:418:17: error: ‘ggml_cuda_pool_free_all’ was not declared in this scope
  418 |                 ggml_cuda_pool_free_all(-1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~

Do you know what I am doing wrong?

**Comment by tomBlueOrange** [comment]
I got it running by running:

`
export CUDACXX=/usr/local/cuda/bin/nvcc
rm -rf build && mkdir build && cd build && cmake -DGGML_CUBLAS=1 .. && cmake --build . --config Release
`

**Comment by cmp-nct** [comment]
Thanks, you were right there was a missing #if in the falcon_main binary for non CUDA compilation.
I'll fix that in a minute
