### ISSUE TITLE
A strange delay happens after about 200 tokens

### ISSUE THREAD

**Issue by cmp-nct** [cmp-nct/ggllm.cpp#15]
I noticed that there is a sudden "stop" of processing after about 200 tokens, then it continues.
I've had it in various models.
Happens with pure CPU as well as with pure GPU processing so it's likely not on GPU side.

**Comment by KerfuffleV2** [comment]
It's probably nothing so obvious, but are you sure it's not hitting the context limit (that would be 512 by default)? If -n > -c then when you hit the -c limit it'll do the context wrap around stuff which can cause a noticeable delay. You probably are aware of that already though.

**Comment by cmp-nct** [comment]
It doesn't appear to be right at the context. Though I am quite sure I had multiple stops at ~200 tokens now I am having them around 501 tokens which is quite close to the default 512.

**Comment by KerfuffleV2** [comment]
Hmm, prompt + generated doesn't add up to the context limit when it happens? For what it's worth, I haven't seen that happen at all. The only issue is the gradual slowdown that occurs, but there's no pause. I also basically always set the context to 2048 as well.

**Comment by cmp-nct** [comment]
Prompt was just 2 tokens.
I also tested lowering ctx and that didn't cause any more frequent slowdowns during large generation.
