### ISSUE TITLE
Parameter --reverse-prompt won't accept text

### ISSUE THREAD

**Issue by BorisEagle** [cmp-nct/ggllm.cpp#24]
# Expected Behavior

Running model wizard-falcon40b.ggmlv3.q4_K_S.bin in interactive mode with argument --reverse-prompt "User:" for model to halt generation if string User: shows in output.

# Current Behavior

Any text added after --reverse-prompt gives error:
error: unknown argument: User:
Model not starting

# Environment and Context

pip list |egrep "torch|numpy|sentencepiece"
numpy                    1.25.0
torch                    2.0.1

AMD Ryzen 7 5800X 8-Core Processor

WSL, Ubuntu 22.04, Linux 5.10.102.1-microsoft-standard-WSL2

Python 3.10.6

# Failure Information (for bugs)

# Steps to Reproduce

1. cd ./build/bin
2. ./falcon_main -r "User:" --threads 14 --model ~/cmp-nct/ggllm.cpp/models/wizard-falcon40b.ggmlv3.q4_K_S.bin --n-predict 150 --temp 0.8 --ctx-size 2048 --n-gpu-layers 10 --interactive --file ~/cmp-nct/ggllm.cpp/prompts/falcon_chat.prompt.txt --keep -1 --color

error: unknown argument: User:

**Comment by cmp-nct** [comment]
It's fixed in latest commit
