### ISSUE TITLE
falcon-main.exe Exits Unexpectedly after 'Numa' Commit

### ISSUE THREAD

**Issue by maddes8cht** [cmp-nct/ggllm.cpp#40]
My last successful build on my Windows machine came from commit 8db9e2c7 "useless warnings"
https://github.com/cmp-nct/ggllm.cpp/commit/8db9e2c736e164ee1db0cc5e192e37d1199bab1b
I compile successfully, run falcon-main.exe and then can get responses in an interactive session.
From the "Numa" commit I can still compile successfully, but after the message
```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to ggLLM.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.
E:\LLama\Falcon>
```
but the program exits and I am back at the terminal command prompt.

I have completely deleted the build directory and done a clean rebuild, but the failure remains.

**Comment by cmp-nct** [comment]
The latest ggml commit changed thread scheduling and added numa. Maybe I missed something

I can run  it -ins but I have not tested it much yet.
Can you give me the exact command line you used ?

In addition if you are able to run it as Debug release, put `gdb --args ` in front of it.
When in GDB shell just enter `r` and if it crashes you can type `bt` to get the location of the problem.

**Comment by cmp-nct** [comment]
Please update, bugfix is out.
Maybe one day we'll have an automated test on github preventing such problems to stick for half a day in code.
Github has such features to compile and test a project.
I just don't have time to dig into that feature yet

Glad you reported it

**Comment by maddes8cht** [comment]
Thanks, you are my personal hero.

Now it works again.
:)
