### ISSUE TITLE
release builds should have other names than "llama-master-codestring.zip"

### ISSUE THREAD

**Issue by maddes8cht** [cmp-nct/ggllm.cpp#43]
Nice to see you've set up binary release builds too.
:)
Now the ames of the binaries are still something like "llama-master-codestring.zip".
I think the whole point of this repo is at least not to be Llama-centric - it should be either falcon-master-xyz" or just "falcon-xyz" or ggllm-cpp-xyz" or something.

It might even get confusing with having llama.cpp and ggllm.cpp release files having all the same names.

**Comment by cmp-nct** [comment]
I setup github actions today, made a range of errors alongside and had a lot of llama.cpp things still lingering in the repo that caused unwanted workflows (such as docker compilations).
I was not aware about the Release, actually it would be cool to have that but I've deleted all workflows.

I currently don't have time but I guess it would be worthwhile to look into the (now deleted) workflow that created the release versions and adapt them for ggllm.cpp

**Comment by cmp-nct** [comment]
So now we have binary releases: https://github.com/cmp-nct/ggllm.cpp/releases/
Currently just for Windows, most people on Linux will have no problems getting it to compile.
