### ISSUE TITLE
Falcon quantization lets you choose q4_k_m, etc but you just get q4_k

### ISSUE THREAD

**Issue by KerfuffleV2** [cmp-nct/ggllm.cpp#7]
In llama.cpp there's logic to choose the quantization based on the type of layer and other heuristics and that controls which layers are q4_k (as an example). It doesn't _just_ quantize everything as q4_k, and that's the difference between q4_k_m, q4_k_l, k4_k_s.

libfalcon's quantize does let you choose the different qN_k types (and will set the file type appropriately) but it just blindly quantizes every layer as q4_k, q3_k etc (except the 1d tensors which are always left 32bit - same as llama.cpp).

Just putting this here as a note and so @thebloke knows he can save some time/bandwidth by only making one qN_k quantization for the time being.

**Comment by TheBloke** [comment]
Oh haha, yeah I just looked at my files and q4_* are all exactly the same size, as are q3_* etc!  I should have spotted that.

OK thanks for the heads up, I'll delete all but one of those so people know there's only one choice atm.

So which should I delete? ie, when I have q4_K_M and q4_K_S both at the same size, are they both q4_K_M or are they both q4_K_S?

**Comment by KerfuffleV2** [comment]
This is the existing llama.cpp logic: https://github.com/ggerganov/llama.cpp/blob/b24c3049d96557c24782e4d32feaae65f47277af/llama.cpp#L2506-L2525

For Q2_K, there's just no equivalent with what the Falcon version is doing currently. Since Q2_K quality was already pretty borderline, this probably is going to mean that the result isn't very usable. The LLaMA version makes some (presumably more important) tensors Q4_K, but the Falcon one just makes _everything_ Q2_K.

For Q3_K, Q4_K, Q5_K the current behavior it would be equivalent to QX_K_S.

Q6_K is the same and didn't have any special logic.

***

I'll add some information here that hopefully might help people with this issue.

The problem here is that Falcon has a different structure and the layers have different names. So deciding which tensors to make higher quality is beyond someone like me. Might be helpful to ask the person that made k-quants to look at it, but I think they devised their current approach for LLaMA after quite a bit of research.

## 40B

### Layer Tensors

Layer tensors start with `transformer.h.N.` where `N` is the layer number.

|Quantized|Name|Shape|Size|
|-|-|-|-|
|N|`ln_attn.weight`|8192|0.031MB|
|N|`ln_attn.bias`|8192|"|
|N|`ln_mlp.weight`|8192|"|
|N|`ln_mlp.bias`|8192|"|
|Y|`self_attention.query_key_value.weight`|8192, 9216|144MB|
|Y|`self_attention.dense.weight`|8192, 8192|128MB|
|Y|`mlp.dense_h_to_4h.weight`|8192, 32768|512MB|
|Y|`mlp.dense_4h_to_h.weight`|32768, 8192|512MB|

We don't have to care about any but the `self_attention.*` and `mlp.*` ones because the others are 1D tensors that are already left as 32bit.

### Root Tensors

|Quantized|Name|Shape|Size|
|-|-|-|-|
|Y|`transformer.word_embeddings.weight`|8192, 65024|1016MB|
|N|`transformer.ln_f.weight`|8192|0.031MB|
|N|`transformer.ln_f.bias`|8192|"|
|Y|`lm_head.weight`|8192, 65024|1016MB|

***

From this, we can see that the biggest size advantage for quantizing is the `mlp.dense_*` tensors in layers and `transformer.word_embeddings.weight`, `lm_head.weight` in the model root. Although, it probably isn't worth highly quantizing those root tensors because because they only account for ~2GB for the whole model.

If I was going to take a guess at a strategy here, I'd use fairly high quality for the root tensors that are going to be quantized. I'd also use fairly high quality for self attention tensors just because they're small and you don't get much by aggressively quantizing them.

Just for comparison, the total of the 16bit layer tensors that I wouldn't quantize aggressively is ~16GB, the total for the `mlp.dense_*` layer tensors is ~60GB.

The LLaMA quantizing logic also places more weight on tensors based on the layer position, I can't really say anything about that part.

**Comment by cmp-nct** [comment]
My comment from our parallel thread:

I think testing it is less of a problem, the machines that can run unquantized falcon (H100, A100 80GB) cost 1.5-2$ per hour.
You can get 48GB variants for less than 60 cents/h and those providers often provide free trials of 100$ which covers quite a lot of testing time.
7B will fit on most GPUs, 40B needs to be squeezed to fit into a 24GB.
I'll test multi GPU next week, once my 2nd one arrives (and if I can squeeze two of those 3-slot monsters in my desktop)

From that point of view I believe Q as well as QK both benefit from mixed precision storage. I'm not talking only about perplexity but also from a parctical point of view.
Consumer GPUs have 8,12,16 or 24 GB of RAM (and next 4090 TI also is 24 GB only) it would make sense to try to get the best possible quality fitting into GPUs.
So people can choose a mixed quantization type based on their hardware.

Those are nice tables btw, it's really helpful to visualize the tensors.

**Comment by TheBloke** [comment]
Thanks very much for the details @KerfuffleV2 

I will remove q3_K_M, q3_K_L, q4_K_M, q5_K_M. And add a note that mentions that the quality of q2_K is doubtful

@cmp-nct if I can help with compute let me know - I can give you access to the H100 system if it'll help with anything.

**Comment by linuxmagic-mp** [comment]
Working on Falcon-40b, having an error with quantize.. Seems like this ticket is already open, and possibly related.  Tell me if you would like a separate ticket opened. 
```
./quantize --leave-output-tensor /home/michael/models/falcon-40b-ggml/ggml-model--f32.bin /home/michael/models/falcon-40b-ggml/ggml-model-qt_k_m.bin Q4_K_M 31
```

```
CUDA Device Summary - 1 devices found
+------------------------------------+------------+-----------+-----------+-----------+-----------+
| Device                             | VRAM Total | VRAM Free | VRAM Used | Split at  | Device ID |
+------------------------------------+------------+-----------+-----------+-----------+-----------+
| NVIDIA GeForce RTX 4090            |   24217 MB |  23636 MB |    581 MB |      0.0% |  0 (Main) |
+------------------------------------+------------+-----------+-----------+-----------+-----------+
Total VRAM: 23.65 GB, Total available VRAM: 23.08 GB
--------------------
main: build = 770 (0eb3604)
main: quantizing '/home/michael/models/falcon-40b-ggml/ggml-model--f32.bin' to '/home/michael/models/falcon-40b-ggml/ggml-model-qt_k_m.bin' as Q4_K_M using 31 threads
llama.cpp: loading model from /home/michael/models/falcon-40b-ggml/ggml-model--f32.bin
llama_model_quantize: failed to quantize: missing tok_embeddings.weight
main: failed to quantize model from '/home/michael/models/falcon-40b-ggml/ggml-model--f32.bin'
```
For the reocrd, I used use-f32 in the falcon_convert.py when I converted it.. 
Recommendations?

**Comment by cmp-nct** [comment]
Do not use quantize, use **falcon_quantize** 

The quantization will be re-worked to be tailored better to falcon in the future
Use the basic types.
q4_k, q5_k, q3_k, q4_0, q4_1 etc

**Comment by linuxmagic-mp** [comment]
That's better, README could be a little clearer, and I get confused as to what parts are trying to get into the main llama.cpp or not.  Running as we speak.. 
```
falcon_model_quantize_internal: model size  = 159591.56 MB
falcon_model_quantize_internal: quant size  = 22449.06 MB

main: quantize time = 168652.82 ms
main:    total time = 168652.82 ms
```
